In [16]:
import pandas as pd
import numpy as np

data={
    'customer_name':['asha','bala','chitra','deepa','esha','bala'],
    'city':['bangalore','delhi','mumbai','delhi','bangalore','delhi'],
    'order_value':[5000,7000,np.nan,6500,7200,7000],
    'email':['asha123@gmail.com','bala@gmail.com','chitra@company.com',
             'deepa_98@yahoo.com','esha@gmail.com','bala@gmail.com']
}

df=pd.DataFrame(data)
df

  customer_name       city  order_value               email
0          asha  bangalore       5000.0   asha123@gmail.com
1          bala      delhi       7000.0      bala@gmail.com
2        chitra     mumbai          NaN  chitra@company.com
3         deepa      delhi       6500.0  deepa_98@yahoo.com
4          esha  bangalore       7200.0      esha@gmail.com
5          bala      delhi       7000.0      bala@gmail.com

Handling duplicate values

Duplicates occur when the same record appears multiple times in a dataset

common reason:
data entry errors
merging datasets
system logging errors

Duplicate can dustrot the analysis, for example:
revenue may appear higher than reality

In [9]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [10]:
#viewing duplicates rows
df[df.duplicated()]

  customer_name   city  order_value           email
5          bala  delhi       7000.0  bala@gmail.com

In [12]:
#removes comletley identical rows
df.drop_duplicates(inplace=True)
df

  customer_name       city  order_value               email
0          asha  bangalore       5000.0   asha123@gmail.com
1          bala      delhi       7000.0      bala@gmail.com
2        chitra     mumbai          NaN  chitra@company.com
3         deepa      delhi       6500.0  deepa_98@yahoo.com
4          esha  bangalore       7200.0      esha@gmail.com

In [19]:
#using subset

df1=df.drop_duplicates(subset='email')
df1

# this removes duplicates only onthe email column

  customer_name       city  order_value               email
0          asha  bangalore       5000.0   asha123@gmail.com
1          bala      delhi       7000.0      bala@gmail.com
2        chitra     mumbai          NaN  chitra@company.com
3         deepa      delhi       6500.0  deepa_98@yahoo.com
4          esha  bangalore       7200.0      esha@gmail.com

In [ ]:
#keep decides which duplicate record remains

df1.drop_duplicates(keep=False)
df1

# keep parameter accepts only three values-first,last,false

  customer_name       city  order_value               email
0          asha  bangalore       5000.0   asha123@gmail.com
1          bala      delhi       7000.0      bala@gmail.com
2        chitra     mumbai          NaN  chitra@company.com
3         deepa      delhi       6500.0  deepa_98@yahoo.com
4          esha  bangalore       7200.0      esha@gmail.com

In [23]:
#string operations with .str

#text column in pandas can use the.str accessor which allows vectorized string operations

df['city'].str.lower()

0    bangalore
1        delhi
2       mumbai
3        delhi
4    bangalore
5        delhi
Name: city, dtype: str

In [27]:
df['customer_name'].str.strip()

#removes extra spaces
#useful when data comes from forms or excel sheets

0      asha
1      bala
2    chitra
3     deepa
4      esha
5      bala
Name: customer_name, dtype: str

In [28]:
df['email'].str.replace('gmail.com','gmail.co')

0      asha123@gmail.co
1         bala@gmail.co
2    chitra@company.com
3    deepa_98@yahoo.com
4         esha@gmail.co
5         bala@gmail.co
Name: email, dtype: str

In [30]:
df['email'].str.split('@')

0     [asha123, gmail.com]
1        [bala, gmail.com]
2    [chitra, company.com]
3    [deepa_98, yahoo.com]
4        [esha, gmail.com]
5        [bala, gmail.com]
Name: email, dtype: object

In [31]:
df['Greeting']="Hello"+df['customer_name']
print(df['Greeting'])

0      Helloasha
1      Hellobala
2    Hellochitra
3     Hellodeepa
4      Helloesha
5      Hellobala
Name: Greeting, dtype: str

In [ ]:
#refex -regular expressions
# To extract patterns from text

common regex patterns

\d          digit
\w          latter or number
^           start of a string
$           end of string



commonly used with-
.str.contains()
.str.extract()
.str.replace()
.str.match()

In [18]:
import pandas as pd

data={"email":["asha123@gmail.com",
                  "bala@gamil.com",
                  "chithra@gmail.com",
                  "deepa_98@gamil.com"]}
df=pd.DataFrame(data)

In [11]:
#extract numbers from text

df["email"].str.extract(r"(\d+)")

     0
0  123
1  NaN
2  NaN
3   98

In [12]:
#find rows containing numbers

df["email"].str.contains(r"\d")

0     True
1    False
2    False
3     True
Name: email, dtype: bool

In [14]:
#extract email domain
df["email"].str.extract(r"@(\w+)")

       0
0  gmail
1  gamil
2  gmail
3  gamil

when we write @(\w+)

() capture group
\w letter or number
+ one or more

here match strats at the symbols @ but since @ is outside of the capture group it is not extract
so only what is inside the capture group () is extracted

In [15]:
#find emails ending with gmail.com

df["email"].str.contains(r"@gmail\.com$")

0     True
1    False
2     True
3    False
Name: email, dtype: bool

In [16]:
data={"Name":["asha","bala","chitra","deepa"]}
df=pd.DataFrame(data)

In [17]:
#find names sarting with A
df["Name"].str.contains(r"^A")

0    False
1    False
2    False
3    False
Name: Name, dtype: bool

In [19]:
#remove numbers from emails

df["email"].str.replace(r"\d","",regex=True)

0       asha@gmail.com
1       bala@gamil.com
2    chithra@gmail.com
3     deepa_@gamil.com
Name: email, dtype: str

In [20]:
#regex groups
#deepa_98@gmail.com
#we want to extract both and number in the email separetly

df["email"].str.extract(r"(\w+)_(\d+)")

       0    1
0    NaN  NaN
1    NaN  NaN
2    NaN  NaN
3  deepa   98