#pandas selection

abel-based selection
#.loc

#used when selecting by row lables a#lnd column names

syntax-
df.loc[row_lable,column_lable]

In [2]:
import pandas as pd
df=pd.read_csv("North America Restaurants (1).csv")
df.head()

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
0,Burger King,Manitowoc,WI,54220,US,"American, Burger, Burgers, Family Meals, Fast ...",True,True,2.4,42
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30

In [3]:
df.loc[0,"name"]

'Burger King'

In [4]:
df.loc[1]

# to select entire row

name                                                            Petro-Canada
city                                                                 Airdrie
state                                                                     AB
zipcode                                                                  T4A
country                                                                   CA
cuisines                   Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...
pickup_enabled                                                          True
delivery_enabled                                                        True
weighted_rating_value                                                    4.1
aggregated_rating_count                                                    1
Name: 1, dtype: object

In [ ]:
df.loc[0:2]

#multiple row
#.loc includes end index

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
0,Burger King,Manitowoc,WI,54220,US,"American, Burger, Burgers, Family Meals, Fast ...",True,True,2.4,42
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88

In [ ]:
df.loc[:,["name","city"]]

#to select specific column data

                                name           city
0                        Burger King      Manitowoc
1                       Petro-Canada        Airdrie
2                           Boba Bae    Ashwaubenon
3               1001 Nights Shawarma      Kitchener
4     Chirpyhut Fried Chicken (JlgJ)       Richmond
...                              ...            ...
1495             Grandma's Soul Food       Richmond
1496                  Jimbob's Pizza     Eau Claire
1497                    Petro-Canada      Longueuil
1498                         Denny's        Kingman
1499                      Bean House  Richmond Hill

[1500 rows x 2 columns]

#loc
position based selection

used when selecting by position

syntax:
df.iloc[row_index,column_index]

In [8]:
df.iloc[0,1]
#selecting single value

'Manitowoc'

In [9]:
df.iloc[0:3,0:2]
#selecting multiple rows and colimns
#iloc excludes end index

           name         city
0   Burger King    Manitowoc
1  Petro-Canada      Airdrie
2      Boba Bae  Ashwaubenon

In [11]:
pd.set_option("display.max_rows",None)

#to display everything

In [13]:
pd.reset_option("display.max_rows")

In [14]:
#boolean masking(filtering)
#filters rows based on condition

df[df["weighted_rating_value"]>2.5]

#singale condition

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30
5,7 West Cafe,Toronto,ON,M4Y 1R4,CA,"2Pour1, 2pour1, Alcohol, Alcool, Allergy Frien...",True,True,4.4,354
...,...,...,...,...,...,...,...,...,...,...
1493,Hungarian Kitchen,North Fort Myers,FL,33917,US,"Desserts, Grocery",False,True,3.0,1
1496,Jimbob's Pizza,Eau Claire,WI,54701,US,"American, Fast Food, Healthy Pizza, Ice Cream ...",False,True,4.1,127
1497,Petro-Canada,Longueuil,QC,J4V,CA,"Convenience, Everyday Essentials, Grocery, Hom...",True,True,4.5,47
1498,Denny's,Kingman,AZ,86401,US,"American, Breakfast And Brunch, Coffee And Tea...",True,True,3.4,22
1499,Bean House,Richmond Hill,ON,L4B 3Z1,CA,"Alcohol, Asian, Asian Fusion, Chinese, Dessert...",True,True,4.8,93

In [17]:
#for multiple conditions

df[(df["weighted_rating_value"]>2.5) & (df["weighted_rating_value"]>3.5)]

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30
5,7 West Cafe,Toronto,ON,M4Y 1R4,CA,"2Pour1, 2pour1, Alcohol, Alcool, Allergy Frien...",True,True,4.4,354
...,...,...,...,...,...,...,...,...,...,...
1490,33 Acres Brewing,Vancouver,BC,V5Y,CA,"Alcohol, Beer, Bière, Boissons Alcoolisées, Ca...",True,True,4.3,1
1492,Golden Chick,Dallas,TX,75217,US,"Bbq, Family Friendly, Family Meals, Fast Food,...",False,True,3.7,116
1496,Jimbob's Pizza,Eau Claire,WI,54701,US,"American, Fast Food, Healthy Pizza, Ice Cream ...",False,True,4.1,127
1497,Petro-Canada,Longueuil,QC,J4V,CA,"Convenience, Everyday Essentials, Grocery, Hom...",True,True,4.5,47
1499,Bean House,Richmond Hill,ON,L4B 3Z1,CA,"Alcohol, Asian, Asian Fusion, Chinese, Dessert...",True,True,4.8,93

In [18]:
#or condition 
df[(df["weighted_rating_value"]>4.5) & (df["pickup_enabled"]==False)]

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
65,Starbucks,Windsor,ON,N8T 1E6,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.7,78
69,Starbucks,St. Catharines,ON,L2N 4H2,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.7,100
172,Starbucks,Halifax,NS,B3S 1P1,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.6,200
248,Starbucks,Kelowna,BC,V1V 2T8,CA,"American, Bakery, Breakfast &Amp; Brunch, Brea...",False,True,4.7,32
290,Sushi Banh Mi Et Poke Ville,Montréal,QC,H2J 1Z5,CA,"Asian, Asiatique, Canadian, Canadien, Chicken,...",False,True,4.8,94
347,Starbucks,West Hollywood,CA,90069,US,"Bakery, Breakfast And Brunch, Cafe, Coffee &Am...",False,True,4.9,165
350,Ab Liquor Outlet,Calgary,AB,T2A 6X7,CA,"Alcohol, Alcool, Beer, Bière, Boissons Alcooli...",False,True,4.9,1
405,Starbucks,Niagara Falls,ON,L2H 0L4,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.8,43
413,Starbucks,Niagara Falls,ON,L2H 1K1,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.6,91
422,Starbucks,Ottawa,ON,K4A 3P7,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.9,71
426,Piesanos - Otow,Ocala,FL,34481,US,"Burger, Chicken, Group Friendly, Italian, Past...",False,True,4.6,152
436,Ab Liquor Outlet,Calgary,AB,T2A 6X7,CA,"Alcohol, Alcool, Beer, Bière, Boissons Alcooli...",False,True,4.9,1
460,Starbucks,Ottawa,ON,K1Y 4S7,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.8,34
476,Hungry Howie's,Gainesville,FL,32608,US,"American, Chicken, Desserts, Healthy, Italian,...",False,True,4.7,93
491,Starbucks,Humble,TX,77346,US,"Bakery, Breakfast And Brunch, Cafe, Coffee &Am...",False,True,4.9,32
570,Starbucks,Vaughan,ON,L6A 4H6,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.6,37
642,Ab Liquor Outlet,Calgary,AB,T2A 6X7,CA,"Alcohol, Alcool, Beer, Bière, Boissons Alcooli...",False,True,4.9,1
663,Starbucks,St. Catharines,ON,L2N 4H2,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.7,100
668,Ab Liquor Outlet,Calgary,AB,T2A 6X7,CA,"Alcohol, Alcool, Beer, Bière, Boissons Alcooli...",False,True,4.9,1
687,Sushi Banh Mi Et Poke Ville,Montréal,QC,H2J 1Z5,CA,"Asian, Asiatique, Canadian, Canadien, Chicken,...",False,True,4.8,94
691,Starbucks,Calgary,AB,T1Y 6M6,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.7,166
696,Starbucks,Edmonton,AB,T6J 5E5,CA,"Bakery, Breakfast And Brunch, Cafe, Cold Coffe...",False,True,4.7,15
710,Culver's,St. Petersburg,FL,33702,US,"American, Burger, Burgers, Comfort Food, Desse...",False,True,4.6,200
722,Starbucks,Toronto,ON,M3J 3N3,CA,"Bakery, Breakfast And Brunch, Cafe, Cold Coffe...",False,True,4.8,78
736,Honey Glazed Hams,Honolulu,HI,96826,US,"American, Dinner, Lunch, Sandwiches, Soup, Wraps",False,True,5.0,55
740,Sushi Banh Mi Et Poke Ville,Montréal,QC,H2J 1Z5,CA,"Asian, Asiatique, Canadian, Canadien, Chicken,...",False,True,4.8,94
747,Starbucks,Barrie,ON,L4N 9H7,CA,"Bakery, Breakfast & Brunch, Breakfast &Amp; Br...",False,True,4.6,28
769,Sushi Banh Mi Et Poke Ville,Montréal,QC,H2J 1Z5,CA,"Asian, Asiatique, Canadian, Canadien, Chicken,...",False,True,4.8,94
792,Five Guys Ms- 488 3840 Promenade Parkway,D&#039;Lberville,MS,39540,US,"American, Burger, Burgers, Desserts, Fast Food...",False,True,4.7,100
801,Five Guys Fl-124,Tampa,FL,33612,US,"American, Burger, Burgers",False,True,4.8,268
820,Starbucks,Amherst,NY,14228,US,"Bakery, Breakfast And Brunch, Cafe, Coffee &Am...",False,True,4.7,133
834,Abe & Mary's,Montréal,QC,H3G,CA,"Beau, Bon, Local, Biologique, Breakfast & Brun...",False,True,4.6,27
843,Five Guys Fl-1500,Fort Myers,FL,33907,US,"American, Burger, Burgers, Group Friendly",False,True,4.9,184
879,Phat Bites2 2730 Lebanon Pike Suite B,Nashville,TN,37214,US,"American, Breakfast, Burger, Burgers, Desserts...",False,True,5.0,74
907,Culver's,St. Petersburg,FL,33713,US,"American, Burger, Burgers, Chicken, Comfort Fo...",False,True,4.7,200
910,Abe & Mary's,Montréal,QC,H3G,CA,"Beau, Bon, Local, Biologique, Breakfast & Brun...",False,True,4.6,27
914,Abe & Mary's,Montréal,QC,H3G,CA,"Beau, Bon, Local, Biologique, Breakfast & Brun...",False,True,4.6,27
946,Chuy's,Gainesville,FL,32608,US,"Chicken, Desserts, Group Friendly, Mexican, Sa...",False,True,4.6,92
957,Kwik Star #715,WATERLOO,IA,50702,US,"Alcohol, American Food, Bakery Food, Breakfast...",False,True,4.7,13
971,Starbucks,Kelowna,BC,V1Y 9G4,CA,"American, Bakery, Breakfast &Amp; Brunch, Coff...",False,True,4.6,54
995,Taqueria La Herradura #1,Pharr,TX,78577,US,"Latin American, Mexican, New Mexican",False,True,4.8,49
1025,Starbucks,Richmond Hill,ON,L4C 7A1,CA,"Bakery, Breakfast And Brunch, Cafe, Cold Coffe...",False,True,4.9,77
1091,Starbucks,Markham,ON,L6C 0G6,CA,"Bakery, Breakfast & Brunch, Breakfast &Amp; Br...",False,True,4.6,29
1095,Starbucks,Newmarket,ON,L3Y 0A4,CA,"Bakery, Breakfast & Brunch, Breakfast &Amp; Br...",False,True,4.6,67
1097,Starbucks,Halifax,NS,B3J 3M7,CA,"Bakery, Breakfast & Brunch, Breakfast &Amp; Br...",False,True,4.7,200
1106,Starbucks,Markham,ON,L6C 0G6,CA,"Bakery, Breakfast & Brunch, Breakfast &Amp; Br...",False,True,4.6,29
1119,Ab Liquor Outlet,Calgary,AB,T2A 6X7,CA,"Alcohol, Alcool, Beer, Bière, Boissons Alcooli...",False,True,4.9,1
1122,Abe & Mary's,Montréal,QC,H3G,CA,"Beau, Bon, Local, Biologique, Breakfast & Brun...",False,True,4.6,27
1137,Starbucks,Reno,NV,89523,US,"Bakery, Breakfast And Brunch, Cafe, Coffee & T...",False,True,4.9,22
1162,Starbucks,Kingston,ON,K7L 1A6,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.8,63
1221,Sushi Banh Mi Et Poke Ville,Montréal,QC,H2J 1Z5,CA,"Asian, Asiatique, Canadian, Canadien, Chicken,...",False,True,4.8,94
1222,Starbucks,Sarnia,ON,N7V 2N6,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.6,37
1237,Sushi Banh Mi Et Poke Ville,Montréal,QC,H2J 1Z5,CA,"Asian, Asiatique, Canadian, Canadien, Chicken,...",False,True,4.8,94
1239,Starbucks,Whitby,ON,L1R 0K6,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.6,65
1333,Abe & Mary's,Montréal,QC,H3G,CA,"Beau, Bon, Local, Biologique, Breakfast & Brun...",False,True,4.6,27
1340,Starbucks,Richmond Hill,ON,L4E 3M2,CA,"Bakery, Breakfast &Amp; Brunch, Breakfast And ...",False,True,4.7,47
1396,Abe & Mary's,Montréal,QC,H3G,CA,"Beau, Bon, Local, Biologique, Breakfast & Brun...",False,True,4.6,27
1406,Sam Falafel And Shawarma,Somerville,MA,2143,US,"Halal, Mediterranean, Middle Eastern, Pizza, S...",False,True,4.8,120
1487,Ab Liquor Outlet,Calgary,AB,T2A 6X7,CA,"Alcohol, Alcool, Beer, Bière, Boissons Alcooli...",False,True,4.9,1

In [ ]:
#not condition
df[(df['country']=='cA')]

Empty DataFrame
Columns: [name, city, state, zipcode, country, cuisines, pickup_enabled, delivery_enabled, weighted_rating_value, aggregated_rating_count]
Index: []

In [4]:
#query method 
#similar sql query

df.query('weighted_rating_value>3.6')

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30
5,7 West Cafe,Toronto,ON,M4Y 1R4,CA,"2Pour1, 2pour1, Alcohol, Alcool, Allergy Frien...",True,True,4.4,354
...,...,...,...,...,...,...,...,...,...,...
1490,33 Acres Brewing,Vancouver,BC,V5Y,CA,"Alcohol, Beer, Bière, Boissons Alcoolisées, Ca...",True,True,4.3,1
1492,Golden Chick,Dallas,TX,75217,US,"Bbq, Family Friendly, Family Meals, Fast Food,...",False,True,3.7,116
1496,Jimbob's Pizza,Eau Claire,WI,54701,US,"American, Fast Food, Healthy Pizza, Ice Cream ...",False,True,4.1,127
1497,Petro-Canada,Longueuil,QC,J4V,CA,"Convenience, Everyday Essentials, Grocery, Hom...",True,True,4.5,47
1499,Bean House,Richmond Hill,ON,L4B 3Z1,CA,"Alcohol, Asian, Asian Fusion, Chinese, Dessert...",True,True,4.8,93

In [ ]:
#multiple condition
df.query('weighted_rating_value>2.6 & country=="CA"')

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30
5,7 West Cafe,Toronto,ON,M4Y 1R4,CA,"2Pour1, 2pour1, Alcohol, Alcool, Allergy Frien...",True,True,4.4,354
6,Petro-Canada,Edmonton,AB,T6X,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.8,1
...,...,...,...,...,...,...,...,...,...,...
1487,Ab Liquor Outlet,Calgary,AB,T2A 6X7,CA,"Alcohol, Alcool, Beer, Bière, Boissons Alcooli...",False,True,4.9,1
1488,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30
1490,33 Acres Brewing,Vancouver,BC,V5Y,CA,"Alcohol, Beer, Bière, Boissons Alcoolisées, Ca...",True,True,4.3,1
1497,Petro-Canada,Longueuil,QC,J4V,CA,"Convenience, Everyday Essentials, Grocery, Hom...",True,True,4.5,47
1499,Bean House,Richmond Hill,ON,L4B 3Z1,CA,"Alcohol, Asian, Asian Fusion, Chinese, Dessert...",True,True,4.8,93

In [8]:
#using variables

limit=4.2
df.query('weighted_rating_value>@limit')

# @ allows python to  use variable inside query

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30
5,7 West Cafe,Toronto,ON,M4Y 1R4,CA,"2Pour1, 2pour1, Alcohol, Alcool, Allergy Frien...",True,True,4.4,354
6,Petro-Canada,Edmonton,AB,T6X,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.8,1
8,Rock Salad,Dubuque,IA,52001,US,"American, Bowls, Dessert, Healthy Food, Salads...",True,True,4.3,35
...,...,...,...,...,...,...,...,...,...,...
1487,Ab Liquor Outlet,Calgary,AB,T2A 6X7,CA,"Alcohol, Alcool, Beer, Bière, Boissons Alcooli...",False,True,4.9,1
1488,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30
1490,33 Acres Brewing,Vancouver,BC,V5Y,CA,"Alcohol, Beer, Bière, Boissons Alcoolisées, Ca...",True,True,4.3,1
1497,Petro-Canada,Longueuil,QC,J4V,CA,"Convenience, Everyday Essentials, Grocery, Hom...",True,True,4.5,47
1499,Bean House,Richmond Hill,ON,L4B 3Z1,CA,"Alcohol, Asian, Asian Fusion, Chinese, Dessert...",True,True,4.8,93

In [ ]:
df.loc[1:5] #loc include iloc  not include

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30
5,7 West Cafe,Toronto,ON,M4Y 1R4,CA,"2Pour1, 2pour1, Alcohol, Alcool, Allergy Frien...",True,True,4.4,354

In [ ]:
df.iloc[1:2] # not include 2

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1