#data transformation

.map() replaces values using a dictionary mapping

map in pandas is used to transform or substiture values ina singale column(series)
using a mapping rule.
commanly used in data cleaning or feature engineering

syntax-series.map(mapping)

here mapping can be another:

dictionary
a function
another series

In [1]:
import pandas as pd
data={"city":
    ["bangalore","delhi","mumbai"]
}
df=pd.DataFrame(data)
df

        city
0  bangalore
1      delhi
2     mumbai

In [13]:
#convert city names to regions
region_map={"bangalore":"south",
             "delhi":"north",
             "mumbai":"west"
              } 

df["region"]=df["city"].map(region_map)
df

        city region
0  bangalore  south
1      delhi  north
2     mumbai   west

In [14]:
#mapping using a function

#.map() can apply a function to each value

df["city_length"]=df["city"].map(len)
df

        city region  city_length
0  bangalore  south            9
1      delhi  north            5
2     mumbai   west            6

In [15]:
#mapping through a series
city_series=pd.Series({"bangalore":"south",
                       "delhi":"north",
                       "mumbai":"west"})

df["region"]=df["city"].map(city_series)
df

        city region  city_length
0  bangalore  south            9
1      delhi  north            5
2     mumbai   west            6

In [16]:
#mapping with missing values
#when there are missing values its filled 
region_map={"bangalore":"south",
             "delhi":"north",
            }

df["region"]=df["city"].map(region_map)
df

        city region  city_length
0  bangalore  south            9
1      delhi  north            5
2     mumbai    NaN            6

In [17]:
#filling missing values using map

df["region"]=df["city"].map(region_map).fillna("other")
df

        city region  city_length
0  bangalore  south            9
1      delhi  north            5
2     mumbai  other            6

In [13]:
import pandas as pd
import numpy as np 

data={"customer":["asha","bala","chitra"],
      "sales":[50000,30000,15000]}

df=pd.DataFrame(data)

In [10]:
#Applying custom functions
#.apply() lets us run custom logic onrows or columns

#example -classify slaes performance

def sales_category(x):
    if x>40000:
        return "high"
    elif x>25000:
        return "medium"
    else:
        return "low"
    
# apply function

df["sales_category"]=df["sales"].apply(sales_category)
df

  customer  sales sales_category
0     asha  50000           high
1     bala  30000         medium
2   chitra  15000            low

In [14]:
#apply with axis 

#axis=0            oparate on column
#axis= 1           operate on rows

df.apply(np.sum,axis=0)
# calculates sum colimn -wise

customer    ashabalachitra
sales                95000
dtype: object

In [7]:
data={
    "a":[10,20,30,40],
    "b":[1,2,3,4]
}

df=pd.DataFrame(data)

In [8]:
df.apply(lambda row:row["a"]+row["b"],axis=1)

#row wise operation

0    11
1    22
2    33
3    44
dtype: int64

In [16]:
#create a column called double_sales using lamba with apply function

df["Double_sales"]=df["sales"].apply(lambda x:x*2)
df

  customer  sales  Double_sales
0     asha  50000        100000
1     bala  30000         60000
2   chitra  15000         30000

In [17]:
#apply on entire dataframe

df.apply(lambda x:x*2)

       customer   sales  Double_sales
0      ashaasha  100000        200000
1      balabala   60000        120000
2  chitrachitra   30000         60000

In [19]:
data={"revenue":[50000,30000],
       "cost":[20000,15000]
       }
df=pd.DataFrame(data)
df

   revenue   cost
0    50000  20000
1    30000  15000

In [20]:
df["profit"]=df.apply(lambda row:row["revenue"]-row["cost"],axis=1)
df

   revenue   cost  profit
0    50000  20000   30000
1    30000  15000   15000

In [22]:
import pandas as pd
import numpy as np 

data={"customer":["asha","bala","chitra"],
      "sales":["50000","30000","15000"]}

df=pd.DataFrame(data)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   customer  3 non-null      str
 1   sales     3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [24]:
#astype -type conversion 
#example-some times numbers might be stored as strings

df["sales"]=df["sales"].astype(int)
df.info()

#converting sales values datatype to numeric

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   customer  3 non-null      str
 1   sales     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [25]:


data={"customer":["asha","bala","chitra"],
      "sales":["50000","30000","missing"]}

df=pd.DataFrame(data)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   customer  3 non-null      str
 1   sales     3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [26]:
pd.to_numeric(df["sales"],errors="coerce")

0    50000.0
1    30000.0
2        NaN
Name: sales, dtype: float64

.apply is a last option or last resort becauese. apply runs python loops internally 

this is not useful when there are millions of rows
in this case we would prefer vectorization(numpy vectorization)

numpy vectorization is faster